var namespaces_dup =
[
    [ "Animation", "namespace_animation.html", "namespace_animation" ],
    [ "App", "namespace_app.html", "namespace_app" ],
    [ "Attr", "namespace_attr.html", "namespace_attr" ],
    [ "Audio", "namespace_audio.html", "namespace_audio" ],
    [ "Base", "namespace_base.html", "namespace_base" ],
    [ "BaseGameFeature", "namespace_base_game_feature.html", "namespace_base_game_feature" ],
    [ "Characters", "namespace_characters.html", "namespace_characters" ],
    [ "Clustering", "namespace_clustering.html", "namespace_clustering" ],
    [ "Commands", "namespace_commands.html", null ],
    [ "Core", "namespace_core.html", "namespace_core" ],
    [ "CoreAnimation", "namespace_core_animation.html", "namespace_core_animation" ],
    [ "CoreGraphics", "namespace_core_graphics.html", "namespace_core_graphics" ],
    [ "Darwin", "namespace_darwin.html", "namespace_darwin" ],
    [ "Db", "namespace_db.html", "namespace_db" ],
    [ "Debug", "namespace_debug.html", "namespace_debug" ],
    [ "Decals", "namespace_decals.html", "namespace_decals" ],
    [ "Dynui", "namespace_dynui.html", "namespace_dynui" ],
    [ "Fibers", "namespace_fibers.html", "namespace_fibers" ],
    [ "Flat", "namespace_flat.html", "namespace_flat" ],
    [ "flatbuffers", "namespaceflatbuffers.html", [
      [ "Pack", "namespaceflatbuffers.html#ab4cd854c1f562710a451c642e9ab0039", null ],
      [ "Pack", "namespaceflatbuffers.html#a10385cbc7686212466061433561bb606", null ],
      [ "Pack", "namespaceflatbuffers.html#ae3f628bc77e7585d01be07a046b5a983", null ],
      [ "Pack", "namespaceflatbuffers.html#ad05f28ad9eb6f36cee0c59ab8b60a44f", null ],
      [ "UnPack", "namespaceflatbuffers.html#a023f67f3891afd73519e800b94855cae", null ],
      [ "UnPack", "namespaceflatbuffers.html#a412e98a60c5ce77f8a0499c65e9ce5aa", null ],
      [ "UnPack", "namespaceflatbuffers.html#a2a14f6dc44e94c97cdfd716b86811ff5", null ],
      [ "UnPack", "namespaceflatbuffers.html#accef1bf665ccacac674663bb15c7440d", null ]
    ] ],
    [ "Fog", "namespace_fog.html", "namespace_fog" ],
    [ "Frame", "namespace_frame.html", "namespace_frame" ],
    [ "FrameSync", "namespace_frame_sync.html", "namespace_frame_sync" ],
    [ "Game", "namespace_game.html", "namespace_game" ],
    [ "GLFW", "namespace_g_l_f_w.html", "namespace_g_l_f_w" ],
    [ "Gltf", "namespace_gltf.html", "namespace_gltf" ],
    [ "Graphics", "namespace_graphics.html", "namespace_graphics" ],
    [ "GraphicsFeature", "namespace_graphics_feature.html", "namespace_graphics_feature" ],
    [ "Http", "namespace_http.html", "namespace_http" ],
    [ "Ids", "namespace_ids.html", "namespace_ids" ],
    [ "Im3d", "namespace_im3d.html", "namespace_im3d" ],
    [ "Input", "namespace_input.html", "namespace_input" ],
    [ "Instancing", "namespace_instancing.html", [
      [ "__ImplementSingleton", "namespace_instancing.html#a7186e437bd29816ba7747eb32f2ee7c2", null ],
      [ "__ImplementSingleton", "namespace_instancing.html#a88337e00baf7965286dd0f2775d5c201", null ]
    ] ],
    [ "Interface", "namespace_interface.html", "namespace_interface" ],
    [ "IO", "namespace_i_o.html", "namespace_i_o" ],
    [ "Jobs", "namespace_jobs.html", "namespace_jobs" ],
    [ "Lighting", "namespace_lighting.html", "namespace_lighting" ],
    [ "Linux", "namespace_linux.html", "namespace_linux" ],
    [ "Materials", "namespace_materials.html", "namespace_materials" ],
    [ "Math", "namespace_math.html", "namespace_math" ],
    [ "MemDb", "namespace_mem_db.html", "namespace_mem_db" ],
    [ "Memory", "namespace_memory.html", "namespace_memory" ],
    [ "Messaging", "namespace_messaging.html", "namespace_messaging" ],
    [ "Models", "namespace_models.html", "namespace_models" ],
    [ "Msg", "namespace_msg.html", null ],
    [ "Net", "namespace_net.html", "namespace_net" ],
    [ "OSX", "namespace_o_s_x.html", "namespace_o_s_x" ],
    [ "Particles", "namespace_particles.html", "namespace_particles" ],
    [ "Physics", "namespace_physics.html", "namespace_physics" ],
    [ "PhysicsFeature", "namespace_physics_feature.html", "namespace_physics_feature" ],
    [ "Picking", "namespace_picking.html", "namespace_picking" ],
    [ "pjson", "namespacepjson.html", null ],
    [ "Posix", "namespace_posix.html", "namespace_posix" ],
    [ "PostEffects", "namespace_post_effects.html", "namespace_post_effects" ],
    [ "Profiling", "namespace_profiling.html", "namespace_profiling" ],
    [ "pybind11", "namespacepybind11.html", "namespacepybind11" ],
    [ "Python", "namespace_python.html", [
      [ "PYBIND11_EMBEDDED_MODULE", "namespace_python.html#ade278397e220c6e753fe1cc2e0e4dcd8", null ],
      [ "PYBIND11_EMBEDDED_MODULE", "namespace_python.html#a80ab862d7660abc963caef51232b7542", null ],
      [ "VariantToPyType", "namespace_python.html#a767c4099b2ad3fe5436263dd193c0051", null ]
    ] ],
    [ "RenderModules", "namespace_render_modules.html", "namespace_render_modules" ],
    [ "RenderUtil", "namespace_render_util.html", "namespace_render_util" ],
    [ "Resources", "namespace_resources.html", "namespace_resources" ],
    [ "Scripting", "namespace_scripting.html", "namespace_scripting" ],
    [ "SoLoud", "namespace_so_loud.html", null ],
    [ "System", "namespace_system.html", "namespace_system" ],
    [ "Terrain", "namespace_terrain.html", "namespace_terrain" ],
    [ "Threading", "namespace_threading.html", "namespace_threading" ],
    [ "TimeManager", "namespace_time_manager.html", null ],
    [ "Timing", "namespace_timing.html", [
      [ "Tick", "namespace_timing.html#a1884fd8969a4a431040692fbcf9f5f1e", null ],
      [ "Time", "namespace_timing.html#a8ad3705944b3f8824d642c4424ab3999", null ],
      [ "SecondsToTicks", "namespace_timing.html#a0e6bf8ecbaa0f52daff8ae2e0676eedf", null ],
      [ "Sleep", "namespace_timing.html#a60ecc2f2142ee97d39169048e5cf29a9", null ],
      [ "TicksToSeconds", "namespace_timing.html#ae00b365e7a8436ebb12705bd633b8234", null ]
    ] ],
    [ "tyti", "namespacetyti.html", "namespacetyti" ],
    [ "Util", "namespace_util.html", "namespace_util" ],
    [ "Vegetation", "namespace_vegetation.html", "namespace_vegetation" ],
    [ "Visibility", "namespace_visibility.html", "namespace_visibility" ],
    [ "Vulkan", "namespace_vulkan.html", "namespace_vulkan" ],
    [ "Win32", "namespace_win32.html", "namespace_win32" ],
    [ "XInput", "namespace_x_input.html", "namespace_x_input" ]
];